sudo: required
services:
  - docker

before_install:
  - docker build -t kimberlymcleod3/docker-react -f Dockerfile.dev .

script:
  - docker run kimberlymcleod3/docker-react npm run test -- --coverage